const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const {JSDOM}=require('jsdom');
const model=require('../workspace-insights');
const {createMaterialsFixture}=require('../dev/materials-fixture');
const root=path.resolve(__dirname,'..');
let checks=0;
function check(name,fn){fn();checks++;console.log('PASS '+name);}
const fixture=createMaterialsFixture();
const p=fixture.read('projects/materials-demo');
check('partial receipt commits only the unreceived value',()=>{const f=model.finance(p);assert.equal(f.materialCommitted,225);assert.equal(f.materialReceived,3885);assert.equal(f.available,22290);});
check('approved budget adjustments and labor commitments are included',()=>{const f=model.finance({...p,laborBudget:10000,laborBudgetDelta:500,materialBudgetDelta:-100,laborSpent:2000,laborCommitted:1000,otherSpent:80});assert.equal(f.budget,36800);assert.equal(f.incurred,5965);assert.equal(f.available,29610);});
check('pending and cancelled orders do not inflate commitments',()=>{const f=model.finance({...p,purchaseOrders:{a:{...p.purchaseOrders['demo-po'],status:'pending_approval'},b:{...p.purchaseOrders['demo-po'],status:'cancelled'}}});assert.equal(f.materialCommitted,0);assert.equal(f.awaitingApproval,4110);});
check('a received and matched invoice is not counted as paid',()=>{const f=model.finance({...p,purchaseOrders:{a:{...p.purchaseOrders['demo-po'],status:'fully_delivered',invoiceAmount:4110,invoiceStatus:'matched'}}});assert.equal(f.markedPaid,0);assert.equal(f.invoiceUnverified,4110);});
check('legacy paid entries reduce only their linked invoice balance',()=>{const f=model.finance({...p,purchaseOrders:{'demo-po':{...p.purchaseOrders['demo-po'],invoiceAmount:4110}},ledger:{a:{poId:'demo-po',status:'paid',total:1000},b:{poId:'other',status:'paid',total:2000}}});assert.equal(f.markedPaid,3000);assert.equal(f.invoiceUnverified,3110);});
const project={...p,tasks:{late:{title:'Ceiling layout',status:'in_progress',dueDate:'2026-09-10',assignedToName:'APM Ana'},review:{title:'Verify framing',status:'for_verification'},done:{title:'Finished task',status:'completed',dueDate:'2026-09-01'}},siteLogs:{log:{logNo:'SL-001',date:'2026-09-12',status:'posted',workAccomplished:'Framing',issues:{one:{description:'Missing drawing',status:'open'}}}},collections:{c:{collectionNo:'COL-001',amount:5000,date:'2026-09-11'}}};
check('actions identify owners and exclude finished tasks',()=>{const a=model.actions(project,new Date('2026-09-12T12:00:00'));assert.ok(a.some(i=>i.id==='late'&&i.owner==='APM Ana'));assert.ok(a.some(i=>i.id==='review'&&i.owner==='PM / Boss'));assert.ok(!a.some(i=>i.id==='done'));assert.ok(a.some(i=>i.id==='log'&&i.action==='Review site report'));assert.ok(!a.some(i=>i.title==='Today’s site update'));});
check('delivery follow-up includes expected date and priority',()=>{const a=model.actions({...p,purchaseOrders:{po:{...p.purchaseOrders['demo-po'],expectedDeliveryDate:'2026-09-10'}}},new Date('2026-09-12T12:00:00'));assert.ok(a.some(i=>i.id==='po'&&i.urgency===3&&i.reason.includes('overdue')));});
check('timeline uses document names and preserves nested site issues',()=>{const r=model.records(project);assert.ok(r.some(i=>i.title==='PO-001 / Batch 1'));assert.ok(r.find(i=>i.collection==='siteLogs').detail.includes('Missing drawing'));});
const source=fs.readFileSync(path.join(root,'workspace.html'),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');
const dom=new JSDOM(source,{url:'http://localhost/',runScripts:'outside-only'}),w=dom.window;
w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.HTMLElement.prototype.scrollIntoView=function(){};
w.firebase=createMaterialsFixture();w._currentUser={uid:'demo-user',name:'Alex Santos',role:'boss'};w._currentPid='materials-demo';
w.requireEdit=()=>true;w.canEditProject=()=>true;w.hidePanelSkeleton=()=>{};w.auditLog=()=>{};w.notifyProject=async()=>{};w.confirm=()=>false;w.isBoss=role=>['boss','owner','admin'].includes(role);w.normalizeRole=r=>r;
w.switchTab=tab=>{w.lastTab=tab};w.toggleExtraTabs=()=>{};
['utils.js','materials.js','materials-workspace.js','workspace-insights.js','sitelog.js','tasks.js'].forEach(file=>vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),dom.getInternalVMContext()));
w.auditLog=()=>{};w.showToast=text=>{w.lastToast=text};w.initMaterials('materials-demo');
const $=id=>w.document.getElementById(id);
const dashboard=w.document.createElement('div');dashboard.id='dashboardPanel';w.document.getElementById('workspaceView').prepend(dashboard);
(async()=>{
  w.renderConnectedWorkspace('materials-demo',project);
  check('mission board renders accurate costs with clickable breakdowns',()=>{assert.ok($('workspaceInsights').textContent.includes('3,885'));assert.ok($('workspaceInsights').textContent.includes('225'));$('workspaceInsights').querySelector('[data-metric="committed"]').click();assert.ok($('projectRecordDialog').textContent.includes('Sample Hardware'));assert.equal($('projectRecordDialog').open,true);$('projectRecordDialog').close();});
  check('search locates material specifications across delivery/order records',()=>{$('workspaceRecordSearch').value='1/8';$('workspaceRecordSearch').dispatchEvent(new w.Event('input'));assert.ok($('workspaceRecordList').textContent.includes('PO-001'));});
  w._currentUser.role='apm';w.renderConnectedWorkspace('materials-demo',project);
  check('APM view excludes financial summaries and client collection search',()=>{assert.equal($('workspaceInsights').querySelector('[data-metric]'),null);$('workspaceRecordSearch').value='COL-001';$('workspaceRecordSearch').dispatchEvent(new w.Event('input'));assert.ok(!$('workspaceRecordList').textContent.includes('COL-001'));});
  check('site update keeps task link and photos with extra fields collapsed',()=>{assert.ok($('logLinkedTask').textContent.includes('Ceiling layout'));assert.equal(w.document.querySelector('.workspace-site-details').open,false);assert.ok($('apmSiteCore').contains($('logWork')));assert.ok($('logPhotoFiles'));});
  w._currentUser.role='boss';$('poSupplier').value='Sample Hardware';$('poSupplierId').value='hardware-a';$('poExpectedDate').value='2026-09-15';w.openMaterialGroup('saved','framing');w.addMaterialGroupToDraft();w.saveMaterialDraft();w.initMaterials('materials-demo');
  check('draft restores lines, hardware and expected delivery date',()=>{assert.equal(w.eval('_draftItems.length'),2);assert.equal($('poSupplierId').value,'hardware-a');assert.equal($('poExpectedDate').value,'2026-09-15');});
  w.initMaterials('different-project');
  check('drafts never bleed into another project',()=>{assert.equal(w.eval('_draftItems.length'),0);assert.equal($('poSupplier').value,'');});
  w.initMaterials('materials-demo');
  w._currentUser.uid='different-user';w.initMaterials('materials-demo');
  check('recovery is isolated by signed-in account',()=>assert.equal(w.eval('_draftItems.length'),0));
  w._currentUser.uid='demo-user';w.initMaterials('materials-demo');
  w.fetchAccessibleProjectsOnce=async()=>[{id:'other-project',name:'Other site',materialGroups:{g:{name:'Flooring',items:[{desc:'Tile',size:'60x60',unit:'box',qty:4}]}},purchaseOrders:{po:{date:'2026-09-12',status:'approved',seq:2,supplierId:'hardware-a',items:[{desc:'Gypsum',size:'9mm',unit:'pcs',qty:2,cost:520}]}}}];
  await $('materialCatalogLoad').onclick();
  check('catalog shares accessible groups while supplier prices retain source and date',()=>{assert.ok($('materialCatalogResults').textContent.includes('Flooring'));const price=w.materialPriceFor({desc:'Gypsum',size:'9mm',unit:'pcs'},'hardware-a');assert.equal(price.cost,520);assert.equal(price.projectName,'Other site');assert.equal(price.date,'2026-09-12');assert.equal(w.materialPriceFor({desc:'Gypsum',size:'9mm',unit:'pcs'},'hardware-b'),null);});
  check('same-day duplicate order detection ignores cancelled orders',()=>{const po=p.purchaseOrders['demo-po'];assert.equal(w.materialDuplicateOrders(p,{supplier:po.supplier,supplierId:po.supplierId,date:po.date,items:po.items}).length,1);assert.equal(w.materialDuplicateOrders({...p,purchaseOrders:{p:{...po,status:'cancelled'}}},{supplier:po.supplier,supplierId:po.supplierId,date:po.date,items:po.items}).length,0);});
  w.eval('_tpid="materials-demo"; _taskCache=[{id:"review",title:"Verify framing",status:"for_verification",progress:100}];');
  w.prompt=()=>'';
  assert.equal(await w.updateTaskStatus('review','in_progress'),false);checks++;console.log('PASS returning a task requires a revision reason');
  await w.updateTaskStatus('review','in_progress',{reason:'Add the missing corner photo'});
  check('revision reason and reviewer are preserved in task history',()=>{const task=w.firebase.read('projects/materials-demo/tasks/review');assert.equal(task.returnReason,'Add the missing corner photo');assert.equal(task.returnedByName,'Alex Santos');assert.ok(Object.values(w.firebase.read('projects/materials-demo/taskEvents')).some(e=>JSON.stringify(e).includes('missing corner photo')));});
  w._currentUser.role='apm';w.eval('_taskCache=[{id:"review",title:"Verify framing",status:"for_verification"}];');
  assert.equal(await w.updateTaskStatus('review','in_progress',{reason:'Return'}),false);checks++;console.log('PASS APM cannot act as the verifying PM');
  w._currentUser.role='boss';w.initSiteLog('materials-demo');$('logDate').value='2026-09-12';$('logWork').value='Framing installed';
  let resolvePosition;Object.defineProperty(w.navigator,'geolocation',{value:{getCurrentPosition:resolve=>{resolvePosition=resolve}},configurable:true});
  let saves=0;w.createSiteLog=async(pid,input)=>{saves++;return{id:'site-one',...input}};
  const first=w.saveLog();const second=w.saveLog();await second;
  assert.equal(saves,0);resolvePosition(null);await first;
  check('repeated submit while geolocation is pending saves one site update',()=>assert.equal(saves,1));
  console.log(JSON.stringify({result:'PASS',checks}));w.close();
})().catch(error=>{console.error(error);w.close();process.exitCode=1});
