const fs = require('fs');
const path = require('path');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const { JSDOM } = require('jsdom');
const { createMaterialsFixture } = require('../dev/materials-fixture');
const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'workspace.html'), 'utf8');
const dom = new JSDOM(source.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,''), { url:'http://localhost/', runScripts:'outside-only' });
const w = dom.window;
w.HTMLDialogElement.prototype.showModal = function(){this.open=true};
w.HTMLDialogElement.prototype.close = function(){this.open=false};
w.firebase=createMaterialsFixture(); w._currentUser={uid:'demo-user',name:'Alex Santos',role:'boss'};
w.requireEdit=()=>true; w.canEditProject=()=>true;w.hidePanelSkeleton=()=>{};w.notifyProject=async()=>{};w.confirm=()=>true;
['utils.js','materials.js','materials-workspace.js'].forEach(file=>vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'), dom.getInternalVMContext()));
w.auditLog=()=>{}; w.showToast=(text)=>{w.lastToast=text};
w.eval('initMaterials("materials-demo")');
const $=id=>w.document.getElementById(id);
let checks=0;
function check(name, fn){fn();checks++;console.log('PASS '+name)}
(async()=>{
  check('default orders view, collapsed stock, usable navigation',()=>{assert.equal($('materialView_orders').hidden,false);assert.equal($('materialView_new').hidden,true);assert.equal(w.document.querySelector('.material-stock-control').open,false);w.showMaterialsView('new');assert.equal($('materialView_new').hidden,false)});
  check('legacy fractional stock paths render all eight named materials',()=>{const text=$('inventoryList').textContent;assert.ok(!text.includes('undefined'));assert.ok(text.includes('Black Screw'));assert.ok(text.includes('Rivets'));assert.equal(w.eval('Object.keys(_inventory).length'),8)});
  check('history shows people and batch numbers, never truncated UIDs',()=>{const text=$('materialMovementBody').textContent;assert.ok(text.includes('Alex Santos'));assert.ok(text.includes('PO-001 / Batch 1'));assert.ok(!text.includes('demo-user'));assert.ok(!text.includes('demo-batch'))});
  check('ledger derives partial delivery without a manual status update',()=>{assert.ok($('ledgerBody').textContent.includes('5 / 8 pcs received'));assert.ok($('ledgerBody').textContent.includes('Partial'))});
  $('poSupplierId').value='hardware-a';$('poSupplier').value='Sample Hardware';
  check('prices are specific to supplier, specification and unit',()=>{assert.equal(w.materialPriceFor({desc:'Gypsum',size:'9mm',unit:'pcs'}).cost,500);assert.equal(w.materialPriceFor({desc:'Gypsum',size:'12mm',unit:'pcs'}),null);assert.equal(w.materialPriceFor({desc:'Gypsum',size:'9mm',unit:'box'}),null);assert.equal(w.materialPriceFor({desc:'Gypsum',size:'9mm',unit:'pcs'},'hardware-b'),null)});
  w.openMaterialGroup('saved','framing');w.addMaterialGroupToDraft();
  check('groups add editable lines and recall hardware prices',()=>{assert.equal(w.eval('_draftItems.length'),2);assert.ok(w.eval('_draftItems.every(item=>item.cost>0)'));assert.equal($('draftList').querySelectorAll('[data-field="qty"]').length,2)});
  w.openMaterialGroup('saved','framing');w.addMaterialGroupToDraft();
  check('adding the same group stacks quantities without duplicate rows',()=>{assert.equal(w.eval('_draftItems.length'),2);assert.equal(w.eval('_draftItems.find(item=>item.desc==="Wall Angle").qty'),16)});
  w.openMaterialGroup('draft');$('materialGroupName').value='Framing + fixings';await w.saveMaterialGroup();
  check('saved groups persist in Firebase and contain no supplier prices',()=>{const groups=w.firebase.read('projects/materials-demo/materialGroups');const saved=Object.values(groups).find(g=>g.name==='Framing + fixings');assert.ok(saved);assert.equal(saved.items.length,2);assert.equal(saved.items[0].cost,undefined)});
  w.initMaterials('materials-demo');
  check('groups survive reinitializing the project',()=>assert.ok($('materialGroupList').textContent.includes('Framing + fixings')));
  await w.openDeliveryModal('demo-po');w.fillRemainingDelivery();
  check('receive all fills only outstanding quantities',()=>{assert.equal($('delQty_3').value,'3');assert.equal($('delQty_0').disabled,true)});
  const first=await w.receiveDelivery('materials-demo','demo-po',{date:'2026-09-11',notes:'Replace one bent angle',media:[{name:'Receipt.jpg',url:'https://example.com/receipt.jpg'}],items:[{index:3,qtyReceived:3,qtyRejected:1,condition:'good'}]});
  check('mixed damaged batch accepts only good stock and stays partial',()=>{assert.equal(first.acceptedCost,150);assert.equal(first.deliveryStatus,'partially_delivered');assert.equal(w.firebase.read('projects/materials-demo/inventory/wall angle||').qtyOnHand,7);assert.equal(w.firebase.read('projects/materials-demo/ledger/row-3').qtyAccepted,7);assert.equal(w.firebase.read('projects/materials-demo/materialSpent'),4035)});
  check('receipt keeps notes and evidence and commits only the replacement value',()=>{const record=w.firebase.read('projects/materials-demo/deliveries/'+first.deliveryId);assert.equal(record.notes,'Replace one bent angle');assert.equal(record.media[0].name,'Receipt.jpg');assert.equal(w.firebase.read('projects/materials-demo/materialCommitted'),75)});
  const final=await w.receiveDelivery('materials-demo','demo-po',{date:'2026-09-11',items:[{index:3,qtyReceived:1,condition:'good'}]});
  check('replacement completes order and updates ledger and spending once',()=>{assert.equal(final.deliveryStatus,'fully_delivered');assert.equal(w.firebase.read('projects/materials-demo/ledger/row-3').status,'delivered');assert.equal(w.firebase.read('projects/materials-demo/materialSpent'),4110);assert.ok(Object.values(w.firebase.read('projects/materials-demo/deliveries')).some(d=>d.deliveryNo==='DR-002'))});
  await assert.rejects(()=>w.receiveDelivery('materials-demo','demo-po',{items:[{index:3,qtyReceived:1}]}),/outstanding/);checks++;console.log('PASS completed order cannot be received again');
  const fixture=createMaterialsFixture();w.firebase=fixture;w.initMaterials('materials-demo');
  await assert.rejects(()=>w.receiveDelivery('materials-demo','demo-po',{items:[{index:3,qtyReceived:4}]}),/remaining/);checks++;console.log('PASS excess delivery rejected');
  await assert.rejects(()=>w.receiveDelivery('materials-demo','demo-po',{items:[{index:3,qtyReceived:1},{index:3,qtyReceived:1}]}),/once/);checks++;console.log('PASS duplicate receipt line rejected');
  await assert.rejects(()=>w.receiveDelivery('materials-demo','demo-po',{items:[{index:3,qtyReceived:1,qtyRejected:2}]}),/Damaged/);checks++;console.log('PASS damaged quantity cannot exceed received');
  check('new stock keys handle fractional sizes and distinguish units',()=>{assert.ok(!/[/.#$\[\]]/.test(w.buildMaterialItemKey({desc:'Screw',size:'1 1/2',unit:'pcs'})));assert.notEqual(w.buildMaterialItemKey({desc:'Screw',unit:'pcs'}),w.buildMaterialItemKey({desc:'Screw',unit:'box'}))});
  await w.updateInventoryFromReceiving('materials-demo',[{desc:'Rivets',size:'1/8',unit:'pcs',qtyAccepted:10,unitCost:1}]);
  check('new receipt reuses old nested stock without erasing history',()=>assert.equal(w.firebase.read('projects/materials-demo/inventory/rivets||1/8').qtyOnHand,110));
  w.requireEdit=()=>false;w.openMaterialGroup('saved','framing');
  check('read-only access cannot open group editor',()=>assert.equal($('materialGroupDialog').open,false));
  console.log(JSON.stringify({result:'PASS',checks}));w.close();
})().catch(error=>{console.error(error);w.close();process.exitCode=1});
