const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const {JSDOM}=require('jsdom');
const model=require('../project-controls');
const {createMaterialsFixture}=require('../dev/materials-fixture');
let checks=0;
function check(name,fn){fn();checks++;console.log('PASS '+name);}
const payment={kind:'supplier',sourceId:'po',type:'payment',amountCents:12345,date:'2026-09-12',reference:'BANK-001',payeeName:'Hardware',notes:'',method:'bank'};
check('money is calculated in centavos',()=>assert.equal(model.cents(123.45),12345));
check('partial payment and credit reduce only the linked obligation',()=>{const b=model.balance({a:payment,b:{...payment,type:'credit',amountCents:500},c:{...payment,sourceId:'other',amountCents:90000}},'supplier','po',200);assert.equal(b.remaining,7155);assert.equal(b.credits,500);});
check('void keeps history and removes the original amount once',()=>{const b=model.balance({a:payment,v:{...payment,type:'void',voids:'a',amountCents:0}},'supplier','po',200);assert.equal(b.remaining,20000);assert.equal(b.history.length,2);});
check('overpayment remains visible as a credit balance',()=>assert.equal(model.balance({a:payment},'supplier','po',100).remaining,-2345));
check('payroll is never inferred paid from finalization',()=>assert.equal(model.balance({},'payroll','log',1000).paid,0));
check('payment validation rejects invalid amount, future date and missing reference',()=>{for(const change of [{amountCents:0},{amountCents:1.5},{date:'2027-01-01'},{reference:''},{kind:'payroll',type:'credit'}])assert.throws(()=>model.validatePayment({...payment,...change},'2026-09-13'));});
check('payroll worker review preserves archived rate and deductions',()=>{const r=model.payrollRows({workerDetails:{w:{name:'Ana',rate:650,gross:3900}},cashAdvancesDeducted:{w:{totalDeduct:500}}});assert.equal(r[0].rate,650);assert.equal(r[0].netCents,340000);});
const item={desc:'Board',size:'9mm',unit:'pcs',qty:10};
const project={materialPlans:{p:{name:'Ceiling',items:[item]}},purchaseOrders:{a:{status:'approved',items:[{...item,planId:'p',qty:4,qtyAccepted:2}]},b:{status:'pending_approval',items:[{...item,planId:'p',qty:3}]},c:{status:'cancelled',items:[{...item,planId:'p',qty:30}]},d:{status:'approved',items:[{...item,planId:'other',qty:100}]}}};
check('planning excludes cancelled orders and other packages and reserves pending quantities',()=>{const row=model.planning(project,'p',project.materialPlans.p)[0];assert.equal(row.ordered,4);assert.equal(row.received,2);assert.equal(row.submitted,3);assert.equal(row.toOrder,3);});
check('planning does not merge specifications or units',()=>{const p=JSON.parse(JSON.stringify(project));p.purchaseOrders.a.items[0].size='12mm';assert.equal(model.planning(p,'p',p.materialPlans.p)[0].ordered,0);});
const source=fs.readFileSync('workspace.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');
const dom=new JSDOM(source,{url:'http://localhost/',runScripts:'outside-only'}),w=dom.window;
w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.HTMLElement.prototype.scrollIntoView=function(){};
w.firebase=createMaterialsFixture();w._currentUser={uid:'demo-user',name:'Alex Santos',role:'boss'};w._currentPid='materials-demo';
w.requireEdit=()=>true;w.canEditProject=()=>true;w.hidePanelSkeleton=()=>{};w.auditLog=()=>{};w.notifyProject=async()=>{};w.confirm=()=>true;w.prompt=()=> 'Wrong amount';w.openEditProjectModal=id=>{w.editOpened=id;};
w.switchTab=()=>{};w.toggleExtraTabs=()=>{};
for(const file of ['utils.js','materials.js','materials-workspace.js','workspace-insights.js','project-controls.js'])vm.runInContext(fs.readFileSync(file,'utf8'),dom.getInternalVMContext(),{filename:file});
w.initMaterials('materials-demo');
const dashboard=w.document.createElement('div');dashboard.id='dashboardPanel';w.document.getElementById('workspaceView').prepend(dashboard);
const fixture=w.firebase;
fixture.put('projects/materials-demo/purchaseOrders/demo-po/invoiceAmount',4110);
fixture.put('projects/materials-demo/payrollLogs/log',{weekStart:'2026-09-07',weekEnd:'2026-09-13',net:3400,workerDetails:{w:{name:'Ana',rate:650,days:6,gross:3900,regular:3900}},cashAdvancesDeducted:{w:{totalDeduct:500}}});
fixture.database().ref('projects/materials-demo').on('value',s=>w.renderConnectedWorkspace('materials-demo',s.val()));
const tick=()=>new Promise(resolve=>setTimeout(resolve,0));
(async()=>{
w.document.getElementById('workspaceEditProject').click();
let renameForm=w.document.querySelector('#projectControlDialog form');renameForm.querySelector('[name=name]').value='Renamed sample project';await renameForm.onsubmit({preventDefault(){},submitter:renameForm.querySelector('[type=submit]')});
check('workspace name edit changes only the project name',()=>{assert.equal(fixture.read('projects/materials-demo/name'),'Renamed sample project');assert.equal(fixture.read('projects/materials-demo/materialBudget'),26400);});
check('payment register separates finalized payroll from payments',()=>assert.match(w.document.getElementById('payrollControlPanel').textContent,/Finalized payroll/));
w.document.querySelector('[data-new-plan]').click();
let form=w.document.getElementById('materialPlanForm');form.querySelector('[name=name]').value='Ceiling package';const group=w.document.getElementById('planGroup');group.value='framing';group.dispatchEvent(new w.Event('change'));
await form.onsubmit({preventDefault(){},submitter:form.querySelector('[type=submit]')});
let plans=fixture.read('projects/materials-demo/materialPlans'),planId=Object.keys(plans)[0];
check('work package saves a material group with planned quantities',()=>assert.equal(plans[planId].items.length,2));
w.document.querySelector('[data-order-plan]').click();w.document.querySelector('[data-order-plan]').click();
check('ordering remaining twice does not double the draft',()=>{const draft=vm.runInContext('_draftItems',dom.getInternalVMContext());assert.equal(draft.length,2);assert.equal(draft[0].planId,planId);assert.equal(draft[0].qty,10);});
check('purchase order normalization retains the plan link',()=>{const row=w.buildPoItem({...item,planId,planName:'Ceiling package'},0);assert.equal(row.planId,planId);});
w.document.querySelector('[data-link-plan]').click();await w.document.querySelector('#projectControlDialog [data-link]').onclick({target:w.document.querySelector('#projectControlDialog [data-link]')});
check('linking an existing order preserves quantities and receipt history',()=>{const lines=fixture.read('projects/materials-demo/purchaseOrders/demo-po/items');assert.equal(lines[1].planId,planId);assert.equal(lines[1].qtyAccepted,10);assert.equal(lines[3].qtyAccepted,5);});
w.openProjectPaymentRecord('payroll','log');
form=w.document.getElementById('paymentEntryForm');for(const [name,value] of Object.entries({amount:'1000',payeeName:'Ana',reference:'PAY-001',notes:'Partial pay'}))form.elements.namedItem(name).value=value;
const submit=form.querySelector('[type=submit]');form.dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:submit}));form.dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:submit}));await tick();
check('double submit records one partial payment with the payee name',()=>{const entries=Object.values(fixture.read('projectPaymentEvents/materials-demo'));assert.equal(entries.length,1);assert.equal(entries[0].amountCents,100000);assert.equal(entries[0].payeeName,'Ana');});
check('payment recording does not modify the payroll snapshot or labor costs',()=>{const p=fixture.read('projects/materials-demo');assert.equal(p.payrollLogs.log.net,3400);assert.equal(p.laborSpent,undefined);});
const voidButton=w.document.querySelector('[data-void]');await voidButton.onclick();
check('correction creates a separate void event and retains the original',()=>{const entries=fixture.read('projectPaymentEvents/materials-demo');assert.equal(Object.keys(entries).length,2);assert.equal(model.balance(entries,'payroll','log',3400).remaining,340000);});
w._currentUser={uid:'apm-user',role:'apm',name:'APM Ana'};w.renderConnectedWorkspace('materials-demo',fixture.read('projects/materials-demo'));
check('APM sees material planning but no payment controls or edit-budget shortcut',()=>{assert.equal(w.document.getElementById('payrollControlPanel').hidden,true);assert.equal(w.document.querySelector('[data-view=payments]').hidden,true);assert.equal(w.document.getElementById('workspaceEditProject'),null);});
w.detachProjectControls();check('cleanup closes dialogs and clears financial content',()=>{assert.equal(w.document.getElementById('projectControlDialog').open,false);assert.equal(w.document.getElementById('payrollControlPanel').textContent,'');});
console.log(JSON.stringify({result:'PASS',checks}));dom.window.close();
})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1;});
